# Generated by Django 3.1.1 on 2020-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chatroom',
            field=models.TextField(max_length=500),
        ),
    ]
