# Generated by Django 3.1.1 on 2020-12-04 08:46

import chat.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_messages_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='token',
            field=models.CharField(default=chat.utils.create_token, max_length=6, unique=True),
        ),
    ]
